language: python

sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6

addons:
  firefox: "62.0.3"
  chrome: stable


before_script:
  - "pip install flake8"
  - "pip install pycodestyle"
  - "flake8 imgqa/*.py && flake8 imgqa/*/*.py"
  - "flake8 Examples/*.py && flake8 Examples/*/*.py"
  - "pycodestyle imgqa/*.py && pycodestyle Examples/*/*.py"
  - "bash chrome_driver_install.sh"

script:
  - pytest Examples/samplerestapitest.py
  - pytest Examples/sampleseleniumtest.py


# deploy:
#   provider: pypi
#   user: Revant
#   password: 
#   distributions: "sdist bdist_wheel"
#   skip_existing: true
#   skip_cleanup: true
#   on:
#       branch: master